spring.application.name=demo

#DataBase Connection
spring.datasource.url=jdbc:postgresql://10.51.16.3:5432/my-gcp-database
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080

base.upload.path=D:\\test\\

gcp.credentials.path=D:/access.json
gcp.bucket.name=testing04
