spring.application.name=demo

#DataBase Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/test
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

base.upload.path=D:\\test\\

gcp.credentials.path=D:/access.json
gcp.bucket.name=testing04
